### ISSUE TITLE
plugin overwrites default alt+l shortcut

### ISSUE THREAD

**Issue by cachaito** [billymoon/LoremIpsum#11]
Hello, I use this shortcut for polish letter "ł" and after installing Your plugin - this keys are binded to lorem_ipsum commnad :-/

Grettings!

**Comment by trwired** [comment]
I just stumbled over this myself. I think that crl+alt+[letter] shortcuts in plugins should be avoided, if possible, as they interfere with certain keyboard mappings for languages such as Polish (here's a nice write-up on how medium.com stumbled over this with their editor: https://medium.com/medium-eng/the-curious-case-of-disappearing-polish-s-fa398313d4df).

Couldn't the shortcut be dropped in favor of the already provided snippet plus the menu option? It's somewhat frustrating when a plugin assumes its functionality is more important than the ability of the user to type certain letter in their mother tongue. ;)

**Comment by billymoon** [comment]
Well, when I wrote it, I kind of wrote it for myself - I never really expected people all over the world would be using it. `ctrl+alt+l` sounds reasonable to me. I like having a keyboard shortcut as I often use it repetitively to get long chunks of lorem ipsum. Pull requests welcome...

**Comment by trwired** [comment]
I'll give it a try. Would a solution where the plugin has a preferences file in which the user is able to set their chosen key bind acceptable? This way it would be possible to set any combination, including `ctrl+alt+l`, for the plugin, yet it would not generate any undesired behavior by coming with a hardcoded arbitrary shortcut.

**Comment by trwired** [comment]
I see there was a similar issue (#2) for Linux users. Given that, and because what I previously offered would be a rather hackish approach, maybe it would be best to make `shift+alt+l` (the shortcut currently used by the Linux flavor of the plugin) for all platforms? Or at least also on Windows.

**Comment by billymoon** [comment]
@trwired yes - I think that would probably be the best - I will accept any pull request to that effect

**Comment by natharduini** [comment]
Unfortunately Shit+Alt+L is the pipe ("|") shortcut on Mac... which I need when writing code.
My solution is not rocket science but in case it's of use to someone...
In User Key Bindings, add the following:
```
{ "keys": ["ctrl+alt+l"], "command": "lorem_ipsum" },
{ "keys": ["shift+alt+l"], "command": "insert", "args": {"characters": "|"} }
```
